-- 1. How many records are there in the sales table?
SELECT COUNT(*) FROM item_sales;

-- 2. How many unique products have been sold?
SELECT COUNT(DISTINCT item_code)
FROM item_sales
WHERE sale_or_return = 'sale';

-- 3. How many sales transactions and return transactions are there?
SELECT sale_or_return, COUNT(sale_or_return) FROM item_sales
GROUP BY sale_or_return;

-- 4. Which products belong to a specific category?
SELECT category_name, item_name, item_code
FROM item_info
ORDER BY 1, 2;

-- 5. Which 10 products were sold the most?
SELECT its.item_code, iti.item_name, COUNT(its.item_code) AS most_sold
FROM item_sales its
JOIN item_info iti ON its.item_code = iti.item_code
WHERE its.sale_or_return = 'sale'
GROUP BY 1, 2
ORDER BY 3 DESC
LIMIT 10;

-- 6. Which category contains the highest number of products?
SELECT category_name, category_code, COUNT(item_code) 
FROM item_info
GROUP BY 1, 2
ORDER BY 3 DESC
LIMIT 1;

-- 7. How many transactions received a discount?
SELECT COUNT(sale_or_return) 
FROM item_sales
WHERE discount = 'Yes';

-- 8. What is the total revenue generated by each product?
SELECT its.item_code, iti.item_name, ROUND(SUM(its.quantity_sold * its.unit_selling_price), 0) AS revenue
FROM item_sales its
JOIN item_info iti ON its.item_code = iti.item_code
WHERE its.sale_or_return = 'sale'
GROUP BY 1, 2
ORDER BY 3 DESC;

-- 9. What is the total revenue generated by each category?
SELECT iti.category_code, iti.category_name, ROUND(SUM(its.quantity_sold * its.unit_selling_price), 0) AS revenue
FROM item_sales its
JOIN item_info iti ON its.item_code = iti.item_code
WHERE its.sale_or_return = 'sale'
GROUP BY 1, 2
ORDER BY 3 DESC;

-- 10. Which 10 products generated the highest revenue?
SELECT its.item_code, iti.item_name, ROUND(SUM(its.quantity_sold * its.unit_selling_price), 0) AS revenue
FROM item_sales its
JOIN item_info iti ON its.item_code = iti.item_code
WHERE its.sale_or_return = 'sale'
GROUP BY 1, 2
ORDER BY 3 DESC
LIMIT 10;

-- 11. Which category generated the highest revenue?
SELECT iti.category_code, iti.category_name, ROUND(SUM(its.quantity_sold * its.unit_selling_price), 0) AS revenue
FROM item_sales its
JOIN item_info iti ON its.item_code = iti.item_code
WHERE its.sale_or_return = 'sale'
GROUP BY 1, 2
ORDER BY 3 DESC
LIMIT 1;

-- 12. What is the average selling price of products in each category?
SELECT iti.category_code, iti.category_name, ROUND(AVG(unit_selling_price),0) AS avg_selling_price
FROM item_sales its
JOIN item_info iti ON its.item_code = iti.item_code
GROUP BY 1, 2
ORDER BY 3;

-- 14. Which products were never sold?
SELECT iti.item_code, iti.item_name
FROM item_info iti
LEFT JOIN item_sales its ON iti.item_code = its.item_code
WHERE its.item_code IS NULL;

-- 15. What is the daily sales trend?
SELECT sale_date, ROUND(SUM(quantity_sold * unit_selling_price), 0) AS revenue  
FROM item_sales
GROUP BY 1
ORDER BY 1, 2;

-- 16. What is the monthly sales trend?
SELECT TO_CHAR(sale_date, 'YYYY/MM'), ROUND(SUM(quantity_sold * unit_selling_price), 0) AS revenue  
FROM item_sales
GROUP BY 1
ORDER BY 1, 2;

-- 17. During which hour of the day are the most sales made?
SELECT EXTRACT(HOUR FROM sale_time), COUNT(sale_or_return) AS most_sales
FROM item_sales
WHERE sale_or_return = 'sale'
GROUP BY 1
ORDER BY 1;

-- 18. Which products are most frequently returned?
SELECT its.item_code, iti.item_name, COUNT(sale_or_return) AS most_returns
FROM item_sales its
JOIN item_info iti ON iti.item_code = its.item_code
WHERE sale_or_return = 'return'
GROUP BY 1, 2
ORDER BY 3 DESC;

-- 19. Which products are sold most often with discounts?
SELECT its.item_code, iti.item_name, COUNT(discount) AS discounts
FROM item_sales its
JOIN item_info iti ON iti.item_code = its.item_code
WHERE discount = 'Yes'
GROUP BY 1, 2
ORDER BY 3 DESC;

-- 20. Which categories contribute the most to discounted sales?
SELECT iti.category_code, iti.category_name,
ROUND(
	SUM(quantity_sold * unit_selling_price) / (SELECT(SUM(quantity_sold * unit_selling_price) * 100.0) 
	FROM item_sales
	WHERE discount = 'Yes'
	AND sale_or_return = 'sale')
	,2) AS revenue_pct
FROM item_sales its
JOIN item_info iti ON iti.item_code = its.item_code
WHERE its.discount = 'Yes'
  AND its.sale_or_return = 'sale'
GROUP BY iti.category_code, iti.category_name
ORDER BY revenue_pct DESC;

-- 21. Find the best-selling product in each category.
WITH best_selling AS(
	SELECT iti.item_name, iti.category_name, SUM(its.quantity_sold) AS total_sold,
	ROW_NUMBER() 
		OVER(PARTITION BY iti.category_name
		ORDER BY COUNT(its.quantity_sold) DESC
		) AS RN
	FROM item_sales its
	JOIN item_info iti ON iti.item_code = its.item_code
	GROUP BY 1, 2
)
SELECT item_name, category_name, total_sold RN
FROM best_selling
WHERE RN = 1;

-- 22. Find the top 3 products in every category by revenue.
WITH top_three AS(
	SELECT iti.item_name, iti.category_name, SUM(its.quantity_sold * its.unit_selling_price) AS revenue,
	ROW_NUMBER() 
		OVER(PARTITION BY iti.category_name
		ORDER BY SUM(its.quantity_sold * its.unit_selling_price)DESC
		) AS RN
	FROM item_sales its
	JOIN item_info iti ON iti.item_code = its.item_code
	GROUP BY 1, 2
)
SELECT item_name, category_name, revenue, RN
FROM top_three
WHERE RN <= 3;

-- 23. Rank all products by total revenue.
WITH rank_all AS(
	SELECT iti.item_code, iti.item_name, SUM(its.quantity_sold * its.unit_selling_price) AS revenue,
	RANK() 
		OVER(ORDER BY SUM(its.quantity_sold * its.unit_selling_price)DESC
		) AS RK
	FROM item_sales its
	JOIN item_info iti ON iti.item_code = its.item_code
	WHERE sale_or_return = 'sale'
	GROUP BY 1, 2
)
SELECT item_code, item_name, revenue, RK
FROM rank_all
ORDER BY RK;

-- 24. Find products whose sales are above the average product sales.
WITH product_revenue AS(
	SELECT iti.item_code, iti.item_name, 
	ROUND(SUM(its.quantity_sold * its.unit_selling_price),2) AS revenue
	FROM item_sales its
	JOIN item_info iti ON iti.item_code = its.item_code
	WHERE sale_or_return = 'sale'
	GROUP BY 1, 2
)
SELECT item_code, item_name, revenue
FROM product_revenue 
WHERE revenue > (
	SELECT ROUND(AVG(revenue),2) FROM product_revenue
)
ORDER BY 3 DESC;

-- 25. Calculate cumulative revenue contribution of products.
WITH cumulative AS(
	SELECT its.sale_date, iti.item_code, iti.item_name, 
	ROUND(SUM(its.quantity_sold * its.unit_selling_price),0) AS revenue
	FROM item_sales its
	JOIN item_info iti ON iti.item_code = its.item_code
	WHERE sale_or_return = 'sale'
	GROUP BY 1, 2, 3
)
SELECT sale_date, item_code, item_name, revenue,
SUM(revenue) OVER(ORDER BY revenue DESC) AS cum_revenue
FROM cumulative
ORDER BY 4 DESC;

-- 26. Which products have the highest loss quantity?
SELECT item_code, item_name, SUM(loss_rate)
FROM loss
GROUP BY 1, 2
ORDER BY 3 DESC;

-- 27. Which categories experience the highest losses?
SELECT iti.category_code, iti.category_name, ROUND(SUM(loss_rate::NUMERIC),0) AS highest_loss
FROM loss l 
JOIN item_info iti ON l.item_code = iti.item_code
GROUP BY 1, 2
ORDER BY 3 DESC;

-- 28. What are the top 10 loss-making products?
SELECT item_code, item_name, ROUND(SUM(loss_rate::NUMERIC),0) AS loss_rate
FROM loss
GROUP BY 1,2 
ORDER BY 3 DESC
LIMIT 10;
